export const BEER_CALL_SUCCESS = "BEER API CALL SUCCESS";
export const BEER_CALL_FAILURE = "BEER API CALL FAILED";

export const USER_CALL_SUCCESS = "ADDRESS API CALL SUCCESS";
export const USER_CALL_FAILURE = "ADDRESS API CALL FAILURE";