export const BEER_CALL_SUCCESS = "BEER API CALL SUCCESS";
export const BEER_CALL_FAILURE = "BEER API CALL FAILED";

export const USER_CALL_SUCCESS = "ADDRESS API CALL SUCCESS";
export const USER_CALL_FAILURE = "ADDRESS API CALL FAILURE";

export const ADD_ITEM_TO_CART = "ITEM ADDED TO CART"
export const REMOVE_ITEM_FROM_CART = "REMOVE ITEM FROM CART"
export const EDIT_ITEM_IN_CART = "EDIT ITEM IN CART"